version: '3'
services:
  app:
    container_name: 'astutecoder-tic-tac-toe-front'
    restart: always
    build: .
    ports:
      - '4568:3000'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1